MODULE scf_algorithms

  INTERFACE DIIS
     SUBROUTINE DIIS_relativistic(EIG,EIGVEC,NBAST,POEFM,PHI,TRSHLD,MAXITR,RESUME)
       USE basis_parameters
       INTEGER,INTENT(IN) :: NBAST
       DOUBLE PRECISION,DIMENSION(NBAST),INTENT(INOUT) :: EIG
       DOUBLE COMPLEX,DIMENSION(NBAST,NBAST),INTENT(INOUT) :: EIGVEC
       DOUBLE COMPLEX,DIMENSION(NBAST*(NBAST+1)/2),INTENT(IN) :: POEFM
       TYPE(twospinor),DIMENSION(NBAST),INTENT(IN) :: PHI
       DOUBLE PRECISION,INTENT(IN) :: TRSHLD
       INTEGER,INTENT(IN) :: MAXITR
       LOGICAL,INTENT(IN) :: RESUME
     END SUBROUTINE DIIS_relativistic

     SUBROUTINE DIIS_RHF(EIG,EIGVEC,NBAST,POEFM,PHI,TRSHLD,MAXITR,RESUME)
       USE basis_parameters
       INTEGER,INTENT(IN) :: NBAST
       DOUBLE PRECISION,DIMENSION(NBAST),INTENT(INOUT) :: EIG
       DOUBLE PRECISION,DIMENSION(NBAST,NBAST),INTENT(INOUT) :: EIGVEC
       DOUBLE PRECISION,DIMENSION(NBAST*(NBAST+1)/2),INTENT(IN) :: POEFM
       TYPE(gaussianbasisfunction),DIMENSION(NBAST),INTENT(IN) :: PHI
       DOUBLE PRECISION,INTENT(IN) :: TRSHLD
       INTEGER,INTENT(IN) :: MAXITR
       LOGICAL,INTENT(IN) :: RESUME
     END SUBROUTINE DIIS_RHF
  END INTERFACE DIIS

  INTERFACE LEVELSHIFTING
     SUBROUTINE LEVELSHIFTING_relativistic(EIG,EIGVEC,NBAST,POEFM,PHI,TRSHLD,MAXITR,RESUME)
       USE basis_parameters
       INTEGER,INTENT(IN) :: NBAST
       DOUBLE PRECISION,DIMENSION(NBAST),INTENT(OUT) :: EIG
       DOUBLE COMPLEX,DIMENSION(NBAST,NBAST),INTENT(OUT) :: EIGVEC
       DOUBLE COMPLEX,DIMENSION(NBAST*(NBAST+1)/2),INTENT(IN) :: POEFM
       TYPE(twospinor),DIMENSION(NBAST),INTENT(IN) :: PHI
       DOUBLE PRECISION,INTENT(IN) :: TRSHLD
       INTEGER,INTENT(IN) :: MAXITR
       LOGICAL,INTENT(IN) :: RESUME
     END SUBROUTINE LEVELSHIFTING_relativistic

     SUBROUTINE LEVELSHIFTING_RHF(EIG,EIGVEC,NBAST,POEFM,PHI,TRSHLD,MAXITR,RESUME)
       USE basis_parameters
       INTEGER,INTENT(IN) :: NBAST
       DOUBLE PRECISION,DIMENSION(NBAST),INTENT(OUT) :: EIG
       DOUBLE PRECISION,DIMENSION(NBAST,NBAST),INTENT(OUT) :: EIGVEC
       DOUBLE PRECISION,DIMENSION(NBAST*(NBAST+1)/2),INTENT(IN) :: POEFM
       TYPE(gaussianbasisfunction),DIMENSION(NBAST),INTENT(IN) :: PHI
       DOUBLE PRECISION,INTENT(IN) :: TRSHLD
       INTEGER,INTENT(IN) :: MAXITR
       LOGICAL,INTENT(IN) :: RESUME
     END SUBROUTINE LEVELSHIFTING_RHF
  END INTERFACE LEVELSHIFTING

  INTERFACE ODA
     SUBROUTINE ODA_RHF(EIG,EIGVEC,NBAST,POEFM,PHI,TRSHLD,MAXITR,RESUME)
       USE basis_parameters
       INTEGER,INTENT(IN) :: NBAST
       DOUBLE PRECISION,DIMENSION(NBAST),INTENT(OUT) :: EIG
       DOUBLE PRECISION,DIMENSION(NBAST,NBAST),INTENT(OUT) :: EIGVEC
       DOUBLE PRECISION,DIMENSION(NBAST*(NBAST+1)/2),INTENT(IN) :: POEFM
       TYPE(gaussianbasisfunction),DIMENSION(NBAST),INTENT(IN) :: PHI
       DOUBLE PRECISION,INTENT(IN) :: TRSHLD
       INTEGER,INTENT(IN) :: MAXITR
       LOGICAL,INTENT(IN) :: RESUME
     END SUBROUTINE ODA_RHF
  END INTERFACE ODA

  INTERFACE ROOTHAAN
     SUBROUTINE ROOTHAAN_relativistic(EIG,EIGVEC,NBAST,POEFM,PHI,TRSHLD,MAXITR,RESUME)
       USE basis_parameters
       INTEGER,INTENT(IN) :: NBAST
       DOUBLE PRECISION,DIMENSION(NBAST),INTENT(OUT) :: EIG
       DOUBLE COMPLEX,DIMENSION(NBAST,NBAST),INTENT(OUT) :: EIGVEC
       DOUBLE COMPLEX,DIMENSION(NBAST*(NBAST+1)/2),INTENT(IN) :: POEFM
       TYPE(twospinor),DIMENSION(NBAST),INTENT(IN) :: PHI
       DOUBLE PRECISION,INTENT(IN) :: TRSHLD
       INTEGER,INTENT(IN) :: MAXITR
       LOGICAL,INTENT(IN) :: RESUME
     END SUBROUTINE ROOTHAAN_relativistic

     SUBROUTINE ROOTHAAN_RHF(EIG,EIGVEC,NBAST,POEFM,PHI,TRSHLD,MAXITR,RESUME)
       USE basis_parameters
       INTEGER,INTENT(IN) :: NBAST
       DOUBLE PRECISION,DIMENSION(NBAST),INTENT(OUT) :: EIG
       DOUBLE PRECISION,DIMENSION(NBAST,NBAST),INTENT(OUT) :: EIGVEC
       DOUBLE PRECISION,DIMENSION(NBAST*(NBAST+1)/2),INTENT(IN) :: POEFM
       TYPE(gaussianbasisfunction),DIMENSION(NBAST),INTENT(IN) :: PHI
       DOUBLE PRECISION,INTENT(IN) :: TRSHLD
       INTEGER,INTENT(IN) :: MAXITR
       LOGICAL,INTENT(IN) :: RESUME
     END SUBROUTINE ROOTHAAN_RHF
  END INTERFACE ROOTHAAN
END MODULE scf_algorithms
