# Basic test framework: compile and run everything
# Antoine Le Hyaric - LJLL Paris 6 - lehyaric@ann.jussieu.fr - 12/2/7

ifndef MODE
MODE = Debug
endif

all:
	cd aspicDataBasesPrinter/build && make
	cd restrictedHartreeFock/build && make
